---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: openstack
spec:
  resources:
  - kind: OperatingSystemConfig
    type: gardenlinux
  # primary: true|false
  # globallyEnabled: true|false # only valid if kind=Extension
  # reconcileTimeout: 30s # only valid if kind=Extension
  deployment:
    deploymentRefs:
    - name: os-gardenlinux # reference to ControllerDeployment
  # policy: OnDemand|Always|AlwaysExceptNoShoots
  # seedSelector:
  #   matchLabels:
  #     foo: bar

